services:
  client:
    container_name: client
    build:
      context: ./build/client
      dockerfile: Dockerfile.mac
    privileged: true
    tty: true
    volumes:
      - ./client:/root/client
    extra_hosts:
      - testdomain.com:192.168.0.11
    networks:
      exploit-network:
        ipv4_address: 192.168.0.10
  target-nginx-server:
    container_name: target-nginx-server
    tty: true
    build:
      context: ./build/nginx
      dockerfile: Dockerfile
    privileged: true
    extra_hosts:
      - testdomain.com:127.0.0.1
    volumes:
      - ./target-nginx:/root/target-nginx
      - ./build/nginx/ssl:/etc/nginx/ssl
    networks:
      exploit-network:
        ipv4_address: 192.168.0.11
  mitm-server:
    container_name: mitm-server
    tty: true
    build:
      context: ./build/mitm
      dockerfile: Dockerfile
    privileged: true
    volumes:
      - ./mitm:/root/mitm
    networks:
      exploit-network:
        ipv4_address: 192.168.0.12
networks:
  exploit-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
